import TabulatorWithRecoil from '../../src';

const colDefs = [
  // {
  //   formatter: 'rowSelection',
  //   titleFormatter: 'rowSelection',
  //   hozAlign: 'center',
  //   headerSort: false,
  //   // titleFormatterParams: {
  //   //   rowRange: 'active', //only toggle the values of the active filtered rows
  //   // },
  // },
  // {
  //   formatter: 'rowSelection',
  //   titleFormatter: 'rowSelection',
  //   hozAlign: 'center',
  //   headerSort: false,
  //   cellClick: function (e, cell) {
  //     cell.getRow().toggleSelect();
  //   },
  // },
  // {
  //   formatter: 'tickbox',
  //   titleFormatter: 'rowSelection',
  //   hozAlign: 'center',
  //   headerSort: false,
  //   // cellClick: function (e, cell) {
  //   //   cell.getRow().toggleSelect();
  //   // },
  // },
  // {
  //   formatter: 'rowSelection',
  //   titleFormatter: 'rowSelection',
  //   hozAlign: 'center',
  //   headerSort: false,
  //   cellClick: function (e, cell) {
  //     cell.getRow().toggleSelect();
  //   },
  // },
  {
    formatter: 'delRowIcon',
    title: '操作',
    hozAlign: 'center',
    width: 60,
    frozen: true,
    formatterParams: {
      action: 'iconDeleteRow',
    },
    cellClick: function (e, cell) {
      cell.getRow().delete();
    },
  },
  {
    title: '姓名',
    field: 'name',
    editor: 'autoComplete',
    editorParams: {
      values: [
        { value: '1', label: 'John' },
        { value: '2', label: 'Jack' },
        { value: '3', label: 'Jane' },
        { value: '4', label: 'Mike' },
      ],
      placeholder: '请输入搜索值',
      mode: 'table',
    },
  },
  {
    title: '身高',
    field: 'height',
    editor: 'multiSelect',
    hozAlign: 'center',
    formatter: 'tags',
    editorParams: {
      values: [
        { value: '1', label: 'John' },
        { value: '2', label: 'Jack' },
        { value: '3', label: 'Jane' },
        { value: '4', label: 'Mike' },
      ],
      placeholder: '请输入搜索值',
    },
  },
  {
    title: '年龄',
    field: 'age',
    editor: 'input',
  },
  {
    title: '性别',
    field: 'gender',
    editor: true,
  },
];

const initData = (() => {
  return new Array(3).fill(0).map((_, i) => ({
    id: i + 1,
    name: `anyone_${i}`,
    age: 12,
    gender: '',
    height: '',
  }));
})();

const uniformProps = {
  tableType: 'tabulator',
  filterDefs: {},
  columnDefs: [
    {
      field: 'name',
      title: '名称',
      headerSort: false,
      editor: true,
    },
    {
      field: 'age',
      title: '年龄',
    },
    {
      field: 'gender',
      title: '性别',
      editor: 'list',
      editorParams: {
        values: [],
      },
    },
  ],
  isRemote: false,
  enableIndexedDBQuery: false,
  data: [
    {
      id: 1,
      name: '潮生',
      age: '12',
      gender: 'male',
      height: 1,
      col: 'red',
      dob: '',
      cheese: 1,
    },
  ],
  remoteAjax: {},
  tableMode: 'editable',
  quickAddConfigs: {
    // data: [
    //   {
    //     ITEM_CODE: 'Y00030000135',
    //     PHARMACY_CODE: '1000000007',
    //     STORE_SUM: '24497',
    //     ITEM_NAME: '阿莫西林胶囊',
    //     CLASS_CODE: 'P',
    //     SPECS: '0.25g*50粒/盒',
    //     USAGE_CODE: null,
    //     ITEM_PRICE: '2.63',
    //     BASE_DOSE: '0.25',
    //     SP_BASE_DOSE: null,
    //     SP_DOSE_UNIT: null,
    //     DOSE_UNIT_CODE: 'g',
    //     MIN_UNIT: '粒',
    //     PACK_QTY: '50',
    //     PACK_UNIT: '盒',
    //     SPELL_CODE: 'AMXLJN',
    //     WB_CODE: 'BASSEG',
    //     SP_SPECS: null,
    //     FREQUENCY_CODE: null,
    //     ITEM_UNIT: '盒',
    //     OPEN_DEPT_CODE: null,
    //     CREATE_APPLY_FORM: '0',
    //     IS_TERMINAL_CONFIRM: '0',
    //     OPERATION_CODE: null,
    //     CHARGE_FLAG: '1',
    //     EXAM_PART: null,
    //     EXAM_CLASS: null,
    //     EXAM_METHOD: null,
    //     LAB_CLASS: null,
    //     LAB_SPECIMEN: null,
    //     EXECUTE_DEPT_CODE: null,
    //     EXAM_DESCRIBE: null,
    //     IS_LONG_ORDER: '1',
    //     OCT_FLAG: '1',
    //     TEST_FLAG: '1',
    //     ONCE_DOSE: '0',
    //     ANTIBIOTIC_LEVEL: null,
    //     CLASS_CODE_NAME: '西药',
    //   },
    //   {
    //     ITEM_CODE: 'Y00030000280',
    //     PHARMACY_CODE: '1000000007',
    //     STORE_SUM: '7497',
    //     ITEM_NAME: '阿莫西林颗粒',
    //     CLASS_CODE: 'P',
    //     SPECS: '0.125g',
    //     USAGE_CODE: null,
    //     ITEM_PRICE: '100',
    //     BASE_DOSE: '0.13',
    //     SP_BASE_DOSE: null,
    //     SP_DOSE_UNIT: null,
    //     DOSE_UNIT_CODE: 'g',
    //     MIN_UNIT: '袋',
    //     PACK_QTY: '15',
    //     PACK_UNIT: '盒',
    //     SPELL_CODE: 'AMXLKL',
    //     WB_CODE: 'BASSJO',
    //     SP_SPECS: null,
    //     FREQUENCY_CODE: null,
    //     ITEM_UNIT: '盒',
    //     OPEN_DEPT_CODE: null,
    //     CREATE_APPLY_FORM: '0',
    //     IS_TERMINAL_CONFIRM: '0',
    //     OPERATION_CODE: null,
    //     CHARGE_FLAG: '1',
    //     EXAM_PART: null,
    //     EXAM_CLASS: null,
    //     EXAM_METHOD: null,
    //     LAB_CLASS: null,
    //     LAB_SPECIMEN: null,
    //     EXECUTE_DEPT_CODE: null,
    //     EXAM_DESCRIBE: null,
    //     IS_LONG_ORDER: '1',
    //     OCT_FLAG: '0',
    //     TEST_FLAG: '0',
    //     ONCE_DOSE: '0',
    //     ANTIBIOTIC_LEVEL: null,
    //     CLASS_CODE_NAME: '西药',
    //   },
    //   {
    //     ITEM_CODE: 'Y00030000427',
    //     PHARMACY_CODE: '1000000007',
    //     STORE_SUM: '3000',
    //     ITEM_NAME: '吉非替尼片',
    //     CLASS_CODE: 'P',
    //     SPECS: '0.25g',
    //     USAGE_CODE: null,
    //     ITEM_PRICE: '257',
    //     BASE_DOSE: '0.25',
    //     SP_BASE_DOSE: null,
    //     SP_DOSE_UNIT: null,
    //     DOSE_UNIT_CODE: 'g',
    //     MIN_UNIT: '片',
    //     PACK_QTY: '10',
    //     PACK_UNIT: '盒',
    //     SPELL_CODE: 'JFTNP',
    //     WB_CODE: 'FDFNT',
    //     SP_SPECS: null,
    //     FREQUENCY_CODE: null,
    //     ITEM_UNIT: '盒',
    //     OPEN_DEPT_CODE: null,
    //     CREATE_APPLY_FORM: '0',
    //     IS_TERMINAL_CONFIRM: '0',
    //     OPERATION_CODE: null,
    //     CHARGE_FLAG: '1',
    //     EXAM_PART: null,
    //     EXAM_CLASS: null,
    //     EXAM_METHOD: null,
    //     LAB_CLASS: null,
    //     LAB_SPECIMEN: null,
    //     EXECUTE_DEPT_CODE: null,
    //     EXAM_DESCRIBE: null,
    //     IS_LONG_ORDER: '1',
    //     OCT_FLAG: '0',
    //     TEST_FLAG: '0',
    //     ONCE_DOSE: '0',
    //     ANTIBIOTIC_LEVEL: null,
    //     CLASS_CODE_NAME: '西药',
    //   },
    //   {
    //     ITEM_CODE: 'Y00030000276',
    //     PHARMACY_CODE: '1000000007',
    //     STORE_SUM: '8517',
    //     ITEM_NAME: '诺氟沙星胶囊',
    //     CLASS_CODE: 'P',
    //     SPECS: '0.1g*24粒/盒',
    //     USAGE_CODE: null,
    //     ITEM_PRICE: '2',
    //     BASE_DOSE: '0.1',
    //     SP_BASE_DOSE: null,
    //     SP_DOSE_UNIT: null,
    //     DOSE_UNIT_CODE: 'g',
    //     MIN_UNIT: '粒',
    //     PACK_QTY: '24',
    //     PACK_UNIT: '盒',
    //     SPELL_CODE: 'NFSXJN',
    //     WB_CODE: 'YRIJEG',
    //     SP_SPECS: null,
    //     FREQUENCY_CODE: null,
    //     ITEM_UNIT: '盒',
    //     OPEN_DEPT_CODE: null,
    //     CREATE_APPLY_FORM: '0',
    //     IS_TERMINAL_CONFIRM: '0',
    //     OPERATION_CODE: null,
    //     CHARGE_FLAG: '1',
    //     EXAM_PART: null,
    //     EXAM_CLASS: null,
    //     EXAM_METHOD: null,
    //     LAB_CLASS: null,
    //     LAB_SPECIMEN: null,
    //     EXECUTE_DEPT_CODE: null,
    //     EXAM_DESCRIBE: null,
    //     IS_LONG_ORDER: '1',
    //     OCT_FLAG: '0',
    //     TEST_FLAG: '0',
    //     ONCE_DOSE: '0',
    //     ANTIBIOTIC_LEVEL: null,
    //     CLASS_CODE_NAME: '西药',
    //   },
    //   {
    //     ITEM_CODE: 'Y00030000143',
    //     PHARMACY_CODE: '1000000007',
    //     STORE_SUM: '4113',
    //     ITEM_NAME: '头孢呋辛酯片',
    //     CLASS_CODE: 'P',
    //     SPECS: '0.25g*12片/盒',
    //     USAGE_CODE: null,
    //     ITEM_PRICE: '4.28',
    //     BASE_DOSE: '0.25',
    //     SP_BASE_DOSE: null,
    //     SP_DOSE_UNIT: null,
    //     DOSE_UNIT_CODE: 'g',
    //     MIN_UNIT: '片',
    //     PACK_QTY: '12',
    //     PACK_UNIT: '盒',
    //     SPELL_CODE: 'TBFXZP',
    //     WB_CODE: 'UBKUST',
    //     SP_SPECS: null,
    //     FREQUENCY_CODE: null,
    //     ITEM_UNIT: '盒',
    //     OPEN_DEPT_CODE: null,
    //     CREATE_APPLY_FORM: '0',
    //     IS_TERMINAL_CONFIRM: '0',
    //     OPERATION_CODE: null,
    //     CHARGE_FLAG: '1',
    //     EXAM_PART: null,
    //     EXAM_CLASS: null,
    //     EXAM_METHOD: null,
    //     LAB_CLASS: null,
    //     LAB_SPECIMEN: null,
    //     EXECUTE_DEPT_CODE: null,
    //     EXAM_DESCRIBE: null,
    //     IS_LONG_ORDER: '1',
    //     OCT_FLAG: '0',
    //     TEST_FLAG: '0',
    //     ONCE_DOSE: '0',
    //     ANTIBIOTIC_LEVEL: null,
    //     CLASS_CODE_NAME: '西药',
    //   },
    //   {
    //     ITEM_CODE: 'Y00030000144',
    //     PHARMACY_CODE: '1000000007',
    //     STORE_SUM: '17094',
    //     ITEM_NAME: '头孢拉定胶囊',
    //     CLASS_CODE: 'P',
    //     SPECS: '0.25g*60粒/瓶',
    //     USAGE_CODE: '001',
    //     ITEM_PRICE: '7.16',
    //     BASE_DOSE: '0.25',
    //     SP_BASE_DOSE: null,
    //     SP_DOSE_UNIT: null,
    //     DOSE_UNIT_CODE: 'g',
    //     MIN_UNIT: '粒',
    //     PACK_QTY: '60',
    //     PACK_UNIT: '瓶',
    //     SPELL_CODE: 'TBLDJN',
    //     WB_CODE: 'UBRPEG',
    //     SP_SPECS: null,
    //     FREQUENCY_CODE: null,
    //     ITEM_UNIT: '瓶',
    //     OPEN_DEPT_CODE: null,
    //     CREATE_APPLY_FORM: '0',
    //     IS_TERMINAL_CONFIRM: '0',
    //     OPERATION_CODE: null,
    //     CHARGE_FLAG: '1',
    //     EXAM_PART: null,
    //     EXAM_CLASS: null,
    //     EXAM_METHOD: null,
    //     LAB_CLASS: null,
    //     LAB_SPECIMEN: null,
    //     EXECUTE_DEPT_CODE: null,
    //     EXAM_DESCRIBE: null,
    //     IS_LONG_ORDER: '1',
    //     OCT_FLAG: '0',
    //     TEST_FLAG: '0',
    //     ONCE_DOSE: '0',
    //     ANTIBIOTIC_LEVEL: null,
    //     CLASS_CODE_NAME: '西药',
    //   },
    //   {
    //     ITEM_CODE: 'Y00030000271',
    //     PHARMACY_CODE: '1000000007',
    //     STORE_SUM: '26481',
    //     ITEM_NAME: '硫酸庆大霉素片',
    //     CLASS_CODE: 'P',
    //     SPECS: '40mg*100片/瓶',
    //     USAGE_CODE: null,
    //     ITEM_PRICE: '15',
    //     BASE_DOSE: '0.04',
    //     SP_BASE_DOSE: null,
    //     SP_DOSE_UNIT: null,
    //     DOSE_UNIT_CODE: 'g',
    //     MIN_UNIT: '片',
    //     PACK_QTY: '100',
    //     PACK_UNIT: '瓶',
    //     SPELL_CODE: 'LSQDMSP',
    //     WB_CODE: 'DSYDFGT',
    //     SP_SPECS: null,
    //     FREQUENCY_CODE: null,
    //     ITEM_UNIT: '瓶',
    //     OPEN_DEPT_CODE: null,
    //     CREATE_APPLY_FORM: '0',
    //     IS_TERMINAL_CONFIRM: '0',
    //     OPERATION_CODE: null,
    //     CHARGE_FLAG: '1',
    //     EXAM_PART: null,
    //     EXAM_CLASS: null,
    //     EXAM_METHOD: null,
    //     LAB_CLASS: null,
    //     LAB_SPECIMEN: null,
    //     EXECUTE_DEPT_CODE: null,
    //     EXAM_DESCRIBE: null,
    //     IS_LONG_ORDER: '1',
    //     OCT_FLAG: '0',
    //     TEST_FLAG: '0',
    //     ONCE_DOSE: '0',
    //     ANTIBIOTIC_LEVEL: null,
    //     CLASS_CODE_NAME: '西药',
    //   },
    //   {
    //     ITEM_CODE: 'Y00030001854',
    //     PHARMACY_CODE: '1000000007',
    //     STORE_SUM: '1484',
    //     ITEM_NAME: '环孢素软胶囊',
    //     CLASS_CODE: 'P',
    //     SPECS: '25mg',
    //     USAGE_CODE: null,
    //     ITEM_PRICE: '396.02',
    //     BASE_DOSE: '25',
    //     SP_BASE_DOSE: null,
    //     SP_DOSE_UNIT: null,
    //     DOSE_UNIT_CODE: 'mg',
    //     MIN_UNIT: '粒',
    //     PACK_QTY: '50',
    //     PACK_UNIT: '盒',
    //     SPELL_CODE: 'HBSRJN',
    //     WB_CODE: 'GBGLEG',
    //     SP_SPECS: null,
    //     FREQUENCY_CODE: null,
    //     ITEM_UNIT: '盒',
    //     OPEN_DEPT_CODE: null,
    //     CREATE_APPLY_FORM: '0',
    //     IS_TERMINAL_CONFIRM: '0',
    //     OPERATION_CODE: null,
    //     CHARGE_FLAG: '1',
    //     EXAM_PART: null,
    //     EXAM_CLASS: null,
    //     EXAM_METHOD: null,
    //     LAB_CLASS: null,
    //     LAB_SPECIMEN: null,
    //     EXECUTE_DEPT_CODE: null,
    //     EXAM_DESCRIBE: null,
    //     IS_LONG_ORDER: '1',
    //     OCT_FLAG: '0',
    //     TEST_FLAG: '0',
    //     ONCE_DOSE: null,
    //     ANTIBIOTIC_LEVEL: null,
    //     CLASS_CODE_NAME: '西药',
    //   },
    //   {
    //     ITEM_CODE: 'Y00030001862',
    //     PHARMACY_CODE: '1000000007',
    //     STORE_SUM: '247',
    //     ITEM_NAME: '他克莫司胶囊',
    //     CLASS_CODE: 'P',
    //     SPECS: '1mg',
    //     USAGE_CODE: null,
    //     ITEM_PRICE: '816.19',
    //     BASE_DOSE: '1',
    //     SP_BASE_DOSE: null,
    //     SP_DOSE_UNIT: null,
    //     DOSE_UNIT_CODE: 'mg',
    //     MIN_UNIT: '粒',
    //     PACK_QTY: '50',
    //     PACK_UNIT: '盒',
    //     SPELL_CODE: 'TKMSJN',
    //     WB_CODE: 'WDANEG',
    //     SP_SPECS: null,
    //     FREQUENCY_CODE: null,
    //     ITEM_UNIT: '盒',
    //     OPEN_DEPT_CODE: null,
    //     CREATE_APPLY_FORM: '0',
    //     IS_TERMINAL_CONFIRM: '0',
    //     OPERATION_CODE: null,
    //     CHARGE_FLAG: '1',
    //     EXAM_PART: null,
    //     EXAM_CLASS: null,
    //     EXAM_METHOD: null,
    //     LAB_CLASS: null,
    //     LAB_SPECIMEN: null,
    //     EXECUTE_DEPT_CODE: null,
    //     EXAM_DESCRIBE: null,
    //     IS_LONG_ORDER: '1',
    //     OCT_FLAG: '0',
    //     TEST_FLAG: '0',
    //     ONCE_DOSE: null,
    //     ANTIBIOTIC_LEVEL: null,
    //     CLASS_CODE_NAME: '西药',
    //   },
    // ],
    data: [
      {
        id: 1,
        name: 'anyone_0',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 2,
        name: 'anyone_1',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 3,
        name: 'anyone_2',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 4,
        name: 'anyone_3',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 5,
        name: 'anyone_4',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 6,
        name: 'anyone_5',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 7,
        name: 'anyone_6',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 8,
        name: 'anyone_7',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 9,
        name: 'anyone_8',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 10,
        name: 'anyone_9',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 11,
        name: 'anyone_10',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 12,
        name: 'anyone_11',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 13,
        name: 'anyone_12',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 14,
        name: 'anyone_13',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 15,
        name: 'anyone_14',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 16,
        name: 'anyone_15',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 17,
        name: 'anyone_16',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 18,
        name: 'anyone_17',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 19,
        name: 'anyone_18',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 20,
        name: 'anyone_19',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 21,
        name: 'anyone_20',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 22,
        name: 'anyone_21',
        age: 12,
        gender: '男',
        height: 95,
      },
      {
        id: 23,
        name: 'anyone_22',
        age: 12,
        gender: '男',
        height: 95,
      },
    ],
    columns: [
      {
        title: '姓名',
        field: 'name',
        headerSort: false,
      },
      {
        title: '年龄',
        field: 'age',
        editor: true,
        hozAlign: 'right',
        headerSort: false,
      },
      {
        title: '性别',
        field: 'gender',
        editor: true,
        headerSort: false,
      },
      {
        title: '身高',
        field: 'height',
        editor: true,
        headerSort: false,
        hozAlign: 'center',
      },
    ],
    // columns: [
    //   {
    //     field: 'ITEM_CODE',
    //     title: '项目编码',
    //     headerSort: false,
    //     width: 150,
    //   },
    //   {
    //     field: 'ITEM_NAME',
    //     title: '项目名称',
    //     headerSort: false,
    //     width: 150,
    //   },
    //   {
    //     field: 'CLASS_CODE_NAME',
    //     title: '类别',
    //     headerSort: false,
    //     width: 100,
    //   },
    //   {
    //     field: 'CLASS_CODE',
    //     title: '项目类型',
    //     headerSort: false,
    //     width: 100,
    //     visible: false,
    //   },
    //   {
    //     field: 'SPECS',
    //     title: '规格',
    //     headerSort: false,
    //     width: 120,
    //   },
    //   {
    //     field: 'USAGE_CODE',
    //     title: '用法',
    //     headerSort: false,
    //     width: 100,
    //     visible: false,
    //   },
    //   {
    //     field: 'ITEM_PRICE',
    //     title: '单价',
    //     headerSort: false,
    //     width: 100,
    //   },
    //   {
    //     field: 'EXAM_PART',
    //     title: '检查部位',
    //     headerSort: false,
    //     width: 100,
    //     visible: false,
    //   },
    //   {
    //     field: 'LAB_CLASS',
    //     title: '检验类型',
    //     headerSort: false,
    //     width: 100,
    //     visible: false,
    //   },
    //   {
    //     field: 'LAB_SPECIMEN',
    //     title: '标本类型',
    //     headerSort: false,
    //     width: 100,
    //     visible: false,
    //   },
    //   {
    //     field: 'BASE_DOSE',
    //     title: '基本剂量',
    //     headerSort: false,
    //     width: 100,
    //   },
    //   {
    //     field: 'SP_DOSE_UNIT',
    //     title: '基本量单位',
    //     headerSort: false,
    //     width: 100,
    //     visible: false,
    //   },
    //   {
    //     field: 'DOSE_UNIT_CODE',
    //     title: '剂量单位',
    //     headerSort: false,
    //     width: 100,
    //     visible: false,
    //   },
    //   {
    //     field: 'MIN_UNIT',
    //     title: '最小单位',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'PACK_QTY',
    //     title: '包装数量',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'PACK_UNIT',
    //     title: '包装单位',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'SPELL_CODE',
    //     title: '项目拼音码',
    //     headerSort: false,
    //     width: 100,
    //     visible: false,
    //   },
    //   {
    //     field: 'WB_CODE',
    //     title: '项目五笔码',
    //     headerSort: false,
    //     width: 100,
    //     visible: false,
    //   },
    //   {
    //     field: 'FREQUENCY_CODE',
    //     title: '默认频次',
    //     headerSort: false,
    //     width: 120,
    //     visible: false,
    //   },
    //   {
    //     field: 'SP_SPECS',
    //     title: '特殊剂量药品规格',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'ITEM_UNIT',
    //     title: '计价单位',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'OPEN_DEPT_CODE',
    //     title: '开立科室',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'CREATE_APPLY_FORM',
    //     title: '是否生成申请单',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'IS_TERMINAL_CONFIRM',
    //     title: '终端确认',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'OPERATION_CODE',
    //     title: '手术编码',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'CHARGE_FLAG',
    //     title: '收费标志',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'EXAM_CLASS',
    //     title: '检查类型',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'EXAM_METHOD',
    //     title: '检查方法',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'SP_DOSE_UNIT',
    //     title: '特殊剂量药品单位',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'SP_BASE_DOSE',
    //     title: '特殊剂量药品基本剂量',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'EXECUTE_DEPT_CODE',
    //     title: '执行科室',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'EXAM_DESCRIBE',
    //     title: '检查具体部位描述',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'OCT_FLAG',
    //     title: '是否处方药',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'TEST_FLAG',
    //     title: '是否皮试',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'ONCE_DOSE',
    //     title: '一次用量',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    //   {
    //     field: 'ANTIBIOTIC_LEVEL',
    //     title: '抗菌药物等级',
    //     headerSort: false,
    //     width: 80,
    //     visible: false,
    //   },
    // ],
    // filters: ['name'],
    filters: ['ITEM_NAME', 'ITEM_CODE', 'SPELL_CODE', 'WB_CODE'],
    uniqueKey: 'ITEM_CODE',
    isRemoteQuery: false,
    remoteQuery: {},
  },
  indexdbConfigs: {},
  commonOptions: {
    selectableRows: 'highlight', //make rows selectable
    // selectable: true,
  },
};

export const CustomEditor = () => {
  return (
    <>
      <div
        style={{
          display: 'flex',
          padding: '32px',
          height: '360px',
          backgroundColor: '#f5f5f5',
        }}
      >
        <TabulatorWithRecoil
          appMode="EDIT"
          widgetId="ss33"
          tableType="tabulator"
          tableMode="editable"
          tabulatorOptions={{
            columns: colDefs,
            data: initData,
          }}
          uniformProps={uniformProps}
          quickAddDropdownDefinitions={{
            data: initData,
            columns: colDefs,
          }}
        />
      </div>
      <div
        style={{
          width: '100%',
          height: '500px',
        }}
      />
      <div
        style={{
          width: '100%',
          height: '500px',
        }}
      />
      <div
        style={{
          width: '100%',
          height: '500px',
        }}
      />
    </>
  );
};
